# Site settings
title: Qwinix Labs
email: kvarma@qwinixtech.com
description: How we work
baseurl: "/qwinix-labs-docs" # the subpath of your site, e.g. /blog/
url: "http://bhagirath-qwnx.github.io" # the base hostname & protocol for your site
twitter_username: qwinix
github_username:  qwinix

# Build settings
markdown: kramdown
